version: "3.8"

services:
  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: auth_admin
     POSTGRES_PASSWORD: supersecret
     POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
